version: '3.7'
services:
  web:
    build: .
    command: make start
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 55301:55301
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: always
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: yo
      POSTGRES_PASSWORD: himitsu
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
volumes:
  redis-data:
  db-data:
